# Site settings
locale:         en
title:          "The Code School"
name:           "The Code School"
email:          
description: >
  The Code School is the place in Cameroon to learn Html and UX.
  Our service is Training, Coaching and Consultant.
baseurl:        "" # the subpath of your site, e.g. /blog/
url:            "http://thecodeschool.xyz"
# twitter_username: thecodeschool
github_username:  TheCodeSchool
facebook_group: 
facebook_page: 

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
paginate: 10
paginate_path: "/blog/page:num/"
google_analytics_id: "UA-"
permalink:      /:categories/:year/:month/:day/:title/

image:          "/images/site_icons/site_icon-256x256.png"
icon:           "/images/site_icons/site_icon-256x256.png"

timezone:       Africa/Douala

author:
  facebook:     BantouTelecom
  twitter:      Bantoutelecom
  google_plus:  Bantoutelecom
fb_admins:      
fb_appid:       

exclude:
  - node_modules
